# -*- coding: utf-8 -*-
"""శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gq8K29i7FIUMOImGvOsM4ufqSWAm5uKj
"""

!unzip "Noto_Serif_Telugu.zip" -d font

!pip install gtts

pip install moviepy opencv-python Pillow numpy

!pip install moviepy

import cv2
import numpy as np
import os
from gtts import gTTS
from PIL import Image, ImageFont, ImageDraw
from moviepy.editor import VideoFileClip, AudioFileClip, concatenate_videoclips
import textwrap # Import the textwrap module
# --- Configuration ---
OUTPUT_FOLDER = "stotra_video_output"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)
TEMP_FOLDER = os.path.join(OUTPUT_FOLDER, "temp")
os.makedirs(TEMP_FOLDER, exist_ok=True)
# Define media paths
telugu_font_path = "font/static/NotoSerifTelugu-Regular.ttf"
image_d1 = "dwadasa.png"
image_d2 = "title.jpg"
image_d3 = "matrica bha.png"
image_d4 = "bhav.png"
image_d5 = "dusa-grampe.png"
image_d6 = "dusa-bakthu.png"
image_d7 = "dusa-grampe1.png"
image_d8 = "dusa-nilvu.png"
image_d9 = "dusa-bakthu1.png"
image_d10 = "dusa-nilvu1.png"
image_d11 = "dusa-yuva1.png"
image_d12 = "dusa-grampe2.png"#final
#image_d13 = "nilvu-kada3.png"
#image_d14 = "nilvu-bakthi.png"
#image_d15 = "nilvu-kada4.png"
#image_d16 = "nilvu-andh.png"
#image_d17 = "bangar-ped2.png"
#image_d18 = "bangar-lak3.png"
#image_d19 = "bangar-lak4.png"
#image_d20 = "bangar-gramasthulj.png"
#image_d21 = "bangar-gramasthu1.png"
#image_d22 = "bangar-jatst.png"
#image_d23 = "bangar-dapp.png"
#image_d24 = "bangar-grmasthulujai.png"
#image_d25 = "bangar-chinni thalli.png"
#image_d26 = "bangar-chinni.png"
#image_d27 = "bangar-mahi.png"
#image_d28 = "bangar-ped3.png"
#image_d29 = "bangar-jaijai.png"
#image_d30 = "bangar-lak0.png"
# --- Story Content (Telugu Script) ---

    #1
story_parts = [
    {
        "title": "The Vedansh Devotional channel",
        "text": [
            "ఇది The Vedansh Devotional ఛానెల్‌లో స్లోకాలు,దివ్యమైన కథలు,ఆలయ విషయాలు మీ కోసం",
            "కలియుగ ప్రత్యక్ష దైవం శ్రీ వేంకటేశ్వర స్వామివారి అపార కృపను పొందించే దివ్య స్తోత్రం!",
            "భక్తిశ్రద్ధలతో శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రాన్ని పారాయణం చేసి గోవిందుని అనుగ్రహాన్ని పొందండి."
        ],
        "image": image_d2
    },
     {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "శ్రీకళ్యాణగుణోల్లాసం చిద్విలాసం మహౌజసం |",
            "శేషాద్రిమస్తకావాసం శ్రీనివాసం భజామహే || 1 ||"
        ],
        "image": image_d1 #/
    },

     {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:కల్యాణగుణాలతో ప్రకాశించే చిదానందరూపుడు, మహాతేజోవంతుడు,",
            "శేషాద్రి శిఖరముపై వాసం చేసే శ్రీనివాసుని భజిస్తున్నాము.",

        ],
        "image": image_d1 #/
    },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "వారాహవేషభూలోకం లక్ష్మీమోహనవిగ్రహం |",
            "వేదాంతగోచరం దేవం వేంకటేశం భజామహే || 2 ||"
        ],
        "image": image_d1 #/
    },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:వారాహావతారంలో భూలోకాన్ని రక్షించినవాడు, లక్ష్మీదేవిని మోహింపజేసిన అందమైన రూపుడు,",
            "వేదాంతవేద్యుడు అయిన వేంకటేశుని నమస్కరిస్తాము."

        ],
        "image": image_d1 #/
    },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "సాంగానామర్చితాకారం ప్రసన్నముఖపంకజం |",
            "విశ్వవిశ్వంభరాధీశం వృషాద్రీశం భజామహే || 3 ||"

        ],
        "image": image_d1 #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:శాస్త్రవేత్తలచే పూజించబడే, పద్మవదనుడైన, విశ్వాధిపతియైన వృషాద్రినాథుని స్మరించుదాం."

        ],
        "image": image_d1 #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "కనత్కనకవేలాఢ్యం కరుణావరుణాలయం |",
            "శ్రీవాసుదేవ చిన్మూర్తిం శేషాద్రీశం భజామహే || 4 ||"
        ],
        "image": image_d1 #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:బంగారు ఆభరణాలతో అలంకరించబడినవాడు, కరుణాసాగరుడు,",
            "చిన్మూర్తియైన వాసుదేవుడు — శేషాద్రినాథుడిని మనసారా ఆరాధించుదాం."
        ],
        "image": image_d1 #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "ఘనాఘనం శేషాద్రిశిఖరానందమందిరం |",
            "శ్రితచాతక సంరక్షం సింహాద్రీశం భజామహే || 5 ||"

        ],
        "image": image_d1    #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:మేఘశ్యామవర్ణుడు, శేషాద్రిశిఖరానందమందిరంలో నివసించే, శరణాగతులను కాపాడే",
            "సింహాద్రినాథుడు మనకు శరణు."

        ],
        "image": image_d1    #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "మంగళప్రదం పద్మాక్షం కస్తూరీతిలకోజ్జ్వలం |",
            "తులస్యాది మనఃపూజ్యం తీర్థాద్రీశం భజామహే || 6 ||"

        ],
        "image": image_d1    #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:మంగళప్రదాత, పద్మనేత్రములు కలవాడు, కస్తూరి తిలకంతో ప్రకాశించే",
            "తీర్థాద్రినాథుడు, తులసీదళాలతో పూజింపబడే వేంకటేశుడు మన రక్షకుడు."

        ],
        "image": image_d1    #/
        },
{
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "స్వామిపుష్కరిణీతీర్థవాసం వ్యాసాదివర్ణితం |",
            "స్వాంఘ్రీసూచితహస్తాబ్జం సత్యరూపం భజామహే || 7 ||"

        ],
        "image": image_d1    #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:స్వామిపుష్కరిణీ తీర్థంలో నివసించే, వ్యాసాదులచే వర్ణింపబడిన, తన",
            "హస్తకమలంతో భక్తులను కాపాడే సత్యరూపుడిని వందిస్తున్నాము."

        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "శ్రీమన్నారాయణం శ్రీశం బ్రహ్మాండాసనతత్పరం |",
            "బ్రహ్మణ్యం సచ్చిదానందం మోహాతీతం భజామహే || 8 ||"

        ],
        "image": image_d1   #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:శ్రీనారాయణుడు, శ్రీపతి, బ్రహ్మాండాధిపతి, సచ్చిదానందస్వరూపుడు,",
            "మోహరహితుడు — ఆ పరమాత్మను స్మరించుదాం."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "అంజనాద్రీశ్వరం లోకరంజనం మునిరంజనం |",
            "భక్తార్తిభంజనం భక్తపారిజాతం తమాశ్రయే || 9 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:అంజనాద్రినాథుడు, లోకాలకు ఆనందదాయకుడు, మునులకూ ప్రియుడు,",
            "భక్తుల కష్టాలను తొలగించే భక్తపారిజాతుడు మన శరణు."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భిల్లీ మనోహర్యం సత్యమనంతం జగతాం విభుం |",
            "నారాయణాచలపతిం సత్యానందం తమాశ్రయే || 10 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:భిల్లీ వనితకు ప్రసన్నుడైన, సత్యస్వరూపుడైన, జగత్పతియైన",
            "నారాయణుడు — ఆనందరూపుడైన వేంకటేశుని స్మరించుదాం."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "చతుర్ముఖత్ర్యంబకాఢ్యం సన్నుతార్య కదంబకం |",
            "బ్రహ్మప్రముఖనిత్రానం ప్రధానపురుషాశ్రయే || 11 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:బ్రహ్మ, రుద్ర, దేవతలచే స్తుతింపబడే, సమస్త దేవతలకు ఆధారమైన",
            "ప్రధానపురుషుడైన వేంకటేశుని ఆశ్రయించుదాం."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "శ్రీమత్పద్మాసనాగ్రస్థ చింతితార్థప్రదాయకం |",
            "లోకైకనాయకం శ్రీమద్వేంకటాద్రీశమాశ్రయే || 12 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:పద్మాసనముపై కూర్చొని భక్తుల చింతితార్థాలను ప్రసాదించే, జగత్తుకు",
            "నాయకుడైన వేంకటాద్రినాథుడిని ఆరాధించుదాం."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "వేంకటాద్రిహరేః స్తోత్రం ద్వాదశశ్లోకసంయుతం |",
            "యః పఠేత్ సతతం భక్త్యా తస్య ముక్తిః కరేస్థితా || 13 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:ఈ ద్వాదశశ్లోకముల వేంకటేశ స్తోత్రం భక్తితో పఠించే వారికి మోక్షం",
            "సులభముగా లభిస్తుంది."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "సర్వపాపహరం ప్రాహుః వేంకటేశస్తదోచ్యతే |",
            "త్వన్నామకో వేంకటాద్రిః స్మరతో వేంకటేశ్వరః |",
            "సద్యః సంస్మరణాదేవ మోక్షసామ్రాజ్యమాప్నుయాత్ || 14 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:వేంకటేశుని నామస్మరణమే పాపనాశనం, ఆయన స్మరణతోనే మోక్షరాజ్యం లభిస్తుంది."
        ],
        "image": image_d1    #/
        },
    {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "వేంకటేశపదద్వంద్యం స్మరామి వ్రజామి సదా |",
            "భూయాః శరణ్యో మే సాక్షాద్దేవేశో భక్తవత్సలః || 15 ||"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "భావం:వేంకటేశుని పాదద్వయాన్ని ఎప్పుడూ స్మరించి, ఆ దేవేశుని శరణుగా తీసుకున్నవారికి",
            "ఆయన కృపా నిత్యముండును."
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "ఇతి శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం |"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "సారాంశం:ఈ ద్వాదశమంజరికా స్తోత్రం శ్రీ వేంకటేశ్వరుని అవతారమహిమను, కరుణను,",
            "సర్వాధికారిత్వాన్ని, భక్తశరణాగత పరమార్థాన్ని సుందరంగా వర్ణిస్తుంది. ప్రతి",
            "శ్లోకం భక్తిలో మునిగిపోయిన సుగంధపుష్పంలా భగవంతుని చరణాలపై"
        ],
        "image": image_d1    #/
        },
         {
        "title": "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం",
        "text": [
            "అర్పించబడినది. ఈ స్తోత్రాన్ని నిత్య పఠనంగా చేసేవారికి పాపక్షయము,",
            "సౌభాగ్యము, మోక్షసాధనము లభిస్తాయి. వేంకటేశుని స్మరణే భక్తికి మూలం, మోక్షానికి మార్గం."
        ],
        "image": image_d1    #/
        }


]
    # --- Video Generation Functions ---
width, height = 1920, 1080
fps = 24

def create_frame(title, subtitle, image_path):
    """Creates a single video frame with text and image."""
    img = Image.new('RGB', (width, height), color='black')
    draw = ImageDraw.Draw(img)
#font
    try:
        font_size_title = 70
        font_size_subtitle = 30
        title_font = ImageFont.truetype(telugu_font_path, font_size_title)
        subtitle_font = ImageFont.truetype(telugu_font_path, font_size_subtitle)
    except IOError:
        print("Warning: Font file not found. Using default font.")
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()

    if os.path.exists(image_path):
        bg_image = Image.open(image_path).resize((int(width * 0.7), int(height * 0.7)), Image.LANCZOS)
        img.paste(bg_image, ((width - bg_image.width) // 2, (height - bg_image.height) // 2))

    if title:
        draw.text((width // 2, 50), title, font=title_font, fill='gold', anchor="mt")

    y_text = height - 200
    # Wrap text and draw each line
    max_width = width - 200 # Adjust this value as needed for padding
    wrapped_lines = []
    for line in subtitle:
        wrapped_lines.extend(textwrap.wrap(line, width=int(max_width / (font_size_subtitle * 0.6)))) # Adjust width based on font size and cast to integer
#change
    for line in wrapped_lines:#Deep Blue with Shadow
        draw.text((width // 2, y_text), line, font=subtitle_font, fill='white', anchor="mt")
        y_text += 60 # Adjust line spacing as needed

    return cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)

def create_scene_video(scene_data, scene_index):
    """Creates a video clip for a single scene with synchronized audio."""
    voiceover_text = " ".join(scene_data["text"])
    audio_path = os.path.join(TEMP_FOLDER, f"scene_{scene_index}.mp3")

    if "Aparajita devia namaha" in voiceover_text:
        tts = gTTS(text=voiceover_text, lang='hi')
    else:
        tts = gTTS(text=voiceover_text, lang='te')

    tts.save(audio_path)

    audio_clip = AudioFileClip(audio_path)
    audio_duration = audio_clip.duration

    video_path = os.path.join(TEMP_FOLDER, f"scene_{scene_index}శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం.mp4")
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(video_path, fourcc, fps, (width, height))

    num_frames = int(audio_duration * fps)

    for _ in range(num_frames):
        frame = create_frame(scene_data["title"], scene_data["text"], scene_data["image"])
        out.write(frame)

    out.release()
    audio_clip.close()

    print(f"Created video for Scene {scene_index} with duration {audio_duration:.2f} seconds.")

    return video_path, audio_path

# --- Main Program Execution ---
if __name__ == "__main__":
    print("Starting video creation process...")

    video_clips = []

    for i, scene in enumerate(story_parts):
        try:
            video_path, audio_path = create_scene_video(scene, i)
            video_clip = VideoFileClip(video_path).set_audio(AudioFileClip(audio_path))
            video_clips.append(video_clip)

        except Exception as e:
            print(f"An error occurred while processing scene {i}: {e}")
            continue

    if video_clips:
        print("\nCombining all scenes into a final video...")
        final_video = concatenate_videoclips(video_clips)

        final_output_path = os.path.join(OUTPUT_FOLDER, "శ్రీ వేంకటేశ్వర ద్వాదశమంజరికా స్తోత్రం.mp4")

        final_video.write_videofile(final_output_path, codec="libx264", audio_codec="aac")

        print(f"\n✅ Video created successfully at: {final_output_path}")

    else:
        print("\n❌ No video clips were created. Exiting.")

    import shutil
    shutil.rmtree(TEMP_FOLDER)
    print("Temporary files have been cleaned up.")

    try:
        from google.colab import files
        files.download(final_output_path)
    except ImportError:
        print("\nNote: The 'google.colab' library is not available. You can find your video file in the 'stotra_video_output' folder on the left-hand side file explorer.")